#.
#.  Read the tutorial at: http://dev.bukkit.org/bukkit-plugins/holographic-displays/
#.
#.  Plugin created by filoghost.
#.
space-between-lines: 0.02
images:
  symbol: '[x]'
  transparency:
    space: ' [|] '
    color: '&7'
bungee:
  refresh-seconds: 3
  use-RedisBungee: false
time:
  format: H:mm
  zone: GMT+1
update-notification: true
debug: false