name: HolographicDisplays
main: com.gmail.filoghost.holographicdisplays.HolographicDisplays
version: 2.3.0

softdepend: [Multiverse-Core, MultiWorld, My Worlds, My_Worlds, ProtocolLib]

commands:
   holograms:
      description: Main command for HolographicDisplays.
      usage: /<command> (Startup error)
      aliases: [hd, holo, hologram, holograms]
